### ISSUE TITLE
役職付与してみよう

### ISSUE THREAD

**Issue by g00cey** [t1una/discord-ofuton#7]
傷病ごとにラベリングするbot

**Comment by g00cey** [comment]
挙動：特定チャンネルに発言されたものを発言者のロールとして設定する。

ロールリスト：
医薬品
医療制度
神経発達障害
統合失調症
双極性障害
抑うつ障害
不安障害
強迫性障害
パニック障害
ストレス因関連障害
解離性障害
摂食障害
睡眠障害
物質関連障害
パーソナリティ障害
セクシャルマイノリティ
その他

**Comment by Yuta0829** [comment]
賛成です
